export const ACTIONS = {
  SET_NUMBER_OF_PLAYERS: 'SET_NUMBER_OF_PLAYERS',
  SET_NUMBER_OF_QUESTIONS: 'SET_NUMBER_OF_QUESTIONS',
  SET_QUESTIONS: 'SET_QUESTIONS',
  SET_ANSWER_ORDER: 'SET_ANSWER_ORDER',
  SET_IS_QUESTIONS_FETCHING: 'SET_IS_QUESTIONS_FETCHING',
  SET_TIMER: 'SET_TIMER',
  SET_CURRENT_QUESTION: 'SET_CURRENT_QUESTION',
  SET_PLAYERS_INFORMATION: 'SET_PLAYERS_INFORMATION',
  SET_HUMAN_PLAYER_ANSWER: 'SET_HUMAN_PLAYER_ANSWER',
  SET_AUTO_PLAYER1_ANSWER: 'SET_AUTO_PLAYER1_ANSWER',
  SET_AUTO_PLAYER2_ANSWER: 'SET_AUTO_PLAYER2_ANSWER',
  SET_AUTO_PLAYER3_ANSWER: 'SET_AUTO_PLAYER3_ANSWER',
  SET_IS_ROUND_FINISHED: 'SET_IS_ROUND_FINISHED',
  RESET_PLAYER_ANSWERS: 'RESET_PLAYER_ANSWERS',
  GET_THE_WINNER: 'GET_THE_WINNER',
  RESET_GAME: "RESET_GAME"
}

export const CONTEXT = {
  QUIZ: 'QUIZ',
}
